.POSIX:

GO=go

check:
	"$(GO)" vet ./...
	gocyclo --over 10 .
	errcheck ./...
	staticcheck --checks=all ./...
	$(MAKE) test

test:
	"$(GO)" test --count=1 --coverprofile='./coverage.txt' --race --shuffle='on' ./...
