'env':
  'BASE_IMAGE': |-
    ${{ vars.BASE_IMAGE || 'adguard/go-builder:1.26.3--1' }}
  'CACHE_BUSTER': |-
    ${{ vars.CACHE_BUSTER || '0' }}
'jobs':
  'LintAndTestJobDocker':
    'if': |
      ${{ github.repository_owner == 'AdGuardSoftwareLimited' }}
    'permissions':
      'contents': 'read'
    'runs-on': 'team-go'
    'steps':
      - 'uses': 'actions/checkout@v6'
        'with':
          # Set to false to avoid GITHUB_TOKEN leaking.
          #
          # See https://github.com/actions/checkout/issues/485#issuecomment-934422611.
          'persist-credentials': false
      - 'name': 'Lint and test step'
        'run': |
          #!/bin/sh

          set -e -f -u -x

          docker build \
              --build-arg "BASE_IMAGE=${BASE_IMAGE}" \
              --build-arg "CACHE_BUSTER=${CACHE_BUSTER}" \
              --output '.' \
              --progress 'plain' \
              --target 'tester-exporter' \
              -f ./docker/ci.Dockerfile \
              .

          exit_code="$(cat ./test-reports/test-exit-code.txt)"
          readonly exit_code

          exit "$exit_code"
  'LintAndTestJobMacOS':
    'if': |
      ${{ github.repository_owner == 'AdGuardSoftwareLimited' }}
    'permissions':
      'contents': 'read'
    'runs-on':
      - 'ephemeral'
      - 'ephemeral-mac'
      - '${{ vars.BUILD_IMAGE_VERSION_MACOS }}'
    'steps':
      - 'uses': 'actions/checkout@v6'
        'with':
          # Set to false to avoid GITHUB_TOKEN leaking.
          #
          # See https://github.com/actions/checkout/issues/485#issuecomment-934422611.
          'persist-credentials': false
      - 'name': 'Lint and test step'
        'run': |
          #!/bin/sh

          set -e -f -u -x

          # NOTE: Only run those checks that only need Go and Go tools.
          make \
              VERBOSE=1 \
              go-deps \
              go-os-check \
              go-lint \
              go-test \
              go-bench \
              go-fuzz \
              ;
  'LintAndTestJobWindows':
    'if': |
      ${{ github.repository_owner == 'AdGuardSoftwareLimited' }}
    'permissions':
      'contents': 'read'
    'runs-on':
      - ephemeral
      - ephemeral-windows
      - registry.int.agrd.dev/windows/windows11-github-go:20260603-0436
    'steps':
      - 'uses': 'actions/checkout@v6'
        'with':
          # Set to false to avoid GITHUB_TOKEN leaking.
          #
          # See https://github.com/actions/checkout/issues/485#issuecomment-934422611.
          'persist-credentials': false
      - 'name': 'Lint and test step'
        'run': |
          set -e -f -u -x

          # NOTE: Only run those checks that only need Go and Go tools.
          make \
              VERBOSE=1 \
              go-deps \
              go-os-check \
              go-lint \
              go-test \
              go-bench \
              go-fuzz \
              ;
        shell: '"C:\Program Files\Git\bin\bash.exe" --noprofile --norc -eo pipefail {0}'
'name': 'Lint and test workflow (private)'
'on':
  'push':
    'branches':
      - '*'
  'workflow_dispatch': null
# Permissions are disabled for all the jobs by default, and then overridden for
# specific jobs if needed.  This is a recommended practice for security reasons,
# and also allows to avoid mistakes with permissions when creating new jobs.
#
# See https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions.
'permissions': { }
